### ISSUE TITLE
Feature enhancement

### ISSUE THREAD

**Issue by tehseensagar** [oddcod3/Phantom-Evasion#8]
It would be great if you add persistence option as well.

Regards
Tehseen

**Comment by oddcod3** [comment]
Yep it's time to include some new features.
I've already developed some new modules (such as a pure C meterpreter payload) which will be included in the next release.
I will try to include also some kind of persistence modules in theese day.

**Comment by oddcod3** [comment]
In your opinion is it better to include some kind of persistence function directly inside the generated executable? (obviously prompting the user to choose if would like to add persistence) or in a secondary file which need to be uploaded  and executed once a sessions has been established?

**Comment by vince-nayal** [comment]
Hi, 

I'd opt for the second choice, so that your session isn't immediately killed upon persistence detection.

**Comment by oddcod3** [comment]
Exactly what i was thinking too since persistence attempt increase behavioural (heuristic) detection it's logic to split payload execution from persistence 
Thank you vince your opinion and collaboration are really usefull

**Comment by oddcod3** [comment]
Also i could implement some kind of polymorphic/junkcode generator (such as junkcode generator already used in phantom evasion C modules)  so every persistence file will be diffrent and also implement some sandbox detection techniques to avoid execution of the persistence file in case of AV dynamic analisys detection

**Comment by oddcod3** [comment]
Even delaying execution with some heavy resource consumption task could be interesting 
Let's see what comes out!

**Comment by oddcod3** [comment]
Phantom Evasion 1.0 released!

**Comment by XxXUnknown** [comment]
Can somebody help me ?
My problem is:
When I open the phantom evasion, two problems appear, the first problem says: [>] Package libc6-dev-i386 [Not found]. And the second says: [Wine] Python not found.
and I press Enter twice, because the same error appears again, then the program opens apparently normal, but when I finish creating the back door, an error appears, and the backdoor is not created.
Help me please, I can not create a back door.
NOTE: I downloaded the latest version of python (version 3).
PHOTOS:
https://ibb.co/dRfYno: first error
https://ibb.co/ezwv08: second error
